portal/models.py
from flask_login import UserMixin
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, String

from hydra_oauth2 import HydraTokenMixin

Base = declarative_base()


def init_app(app):
    from .db import session

    # ensure that the db session is closed and disposed after each request
    @app.teardown_appcontext
    def discard_session(exc):
        session.remove()


class User(UserMixin, Base):
    __tablename__ = 'user'
    id = Column(String, primary_key=True)
    email = Column(String, nullable=False)


class HydraToken(HydraTokenMixin, Base):
    pass

portal/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField
from wtforms.validators import input_required


class MetadataRecordForm(FlaskForm):

    collection_key = StringField(
        label='Metadata collection',
        validators=[input_required()],
    )

    schema_key = StringField(
        label='Metadata schema',
        validators=[input_required()],
    )

    metadata = TextAreaField(
        label='Metadata dictionary',
        validators=[input_required()],
    )

    doi = StringField(
        label='DOI',
    )

    auto_assign_doi = BooleanField(
        label='Auto-assign DOI?',
    )

portal/__init__.py
from flask import Flask
from flask_login import LoginManager

from . import models, views, cli, config, hydra, db

app = Flask(__name__)
app.config.from_object(config.Config)

models.init_app(app)
views.init_app(app)
cli.init_app(app)
hydra.init_app(app)

login_manager = LoginManager()
login_manager.login_view = 'hydra.login'
login_manager.init_app(app)


@login_manager.user_loader
def load_user(user_id):
    return db.session.query(models.User).get(user_id)

portal/views.py
import json

from flask import render_template, Blueprint, request, current_app, flash, abort
from flask_login import login_required
from flask.helpers import get_env
import requests

from .hydra import get_access_token
from .forms import MetadataRecordForm

bp = Blueprint('portal', __name__)


def init_app(app):
    app.register_blueprint(bp)


@bp.route('/')
def index():
    return render_template('home.html')


@bp.route('/institutions/')
@login_required
def list_institutions():
    results = _accountsapi_request('GET', '/institution/')
    return render_template('institutions.html', institutions=results or [])


@bp.route('/<institution_key>/list_records')
@login_required
def list_records(institution_key: str):
    results = _odpapi_request('GET', f'/{institution_key}/metadata/')
    return render_template('list_records.html', institution_key=institution_key, records=results or [])


@bp.route('/<institution_key>/view_record/<record_id>')
@login_required
def view_record(institution_key: str, record_id: str):
    result = _odpapi_request('GET', f'/{institution_key}/metadata/{record_id}')
    if result:
        result = json.dumps(result, indent=4)
    return render_template('view_record.html', institution_key=institution_key, record=result)


@bp.route('/<institution_key>/add_record', methods=('GET', 'POST'))
@login_required
def add_record(institution_key: str):
    result = None
    form = MetadataRecordForm()
    if request.method == 'POST':
        if form.validate():
            result = _odpapi_request('POST', f'/{institution_key}/metadata/', json={
                'collection_key': form.collection_key.data,
                'schema_key': form.schema_key.data,
                'metadata': json.loads(form.metadata.data),
                'doi': form.doi.data,
                'auto_assign_doi': form.auto_assign_doi.data,
            })
            if result:
                result = json.dumps(result, indent=4)

    return render_template('edit_record.html', institution_key=institution_key, record=result, form=form, new=True)


@bp.route('/<institution_key>/edit_record/<record_id>', methods=('GET', 'POST'))
@login_required
def edit_record(institution_key: str, record_id: str):
    result = None
    if request.method == 'GET':
        record = _odpapi_request('GET', f'/{institution_key}/metadata/{record_id}')
        if not record:
            abort(404)
        record['metadata'] = json.dumps(record['metadata'], indent=4)
        form = MetadataRecordForm(**record)
    else:
        form = MetadataRecordForm()
        if form.validate():
            result = _odpapi_request('PUT', f'/{institution_key}/metadata/{record_id}', json={
                'collection_key': form.collection_key.data,
                'schema_key': form.schema_key.data,
                'metadata': json.loads(form.metadata.data),
                'doi': form.doi.data,
                'auto_assign_doi': form.auto_assign_doi.data,
            })
            if result:
                result = json.dumps(result, indent=4)

    return render_template('edit_record.html', institution_key=institution_key, record=result, form=form, new=False)


def _odpapi_request(method, endpoint, **kwargs):
    return _request(current_app.config['ODP_API_URL'], 'ODP API', method, endpoint, **kwargs)


def _accountsapi_request(method, endpoint, **kwargs):
    return _request(current_app.config['ACCOUNTS_API_URL'], 'Accounts API', method, endpoint, **kwargs)


def _request(api_url, api_name, method, endpoint, **kwargs):
    ckanapi_key = current_app.config['CKAN_API_KEY']
    access_token = ckanapi_key or get_access_token()
    verify_tls = get_env() != 'development'
    timeout = None if get_env() == 'development' else 10
    headers = {
        'Accept': 'application/json',
        'Authorization': 'Bearer ' + access_token,
    }
    if method in ('POST', 'PUT'):
        headers['Content-Type'] = 'application/json'
    headers.update(kwargs.pop('headers', {}))
    try:
        r = requests.request(method, api_url + endpoint, **kwargs,
                             headers=headers,
                             verify=verify_tls,
                             timeout=timeout,
                             )
        r.raise_for_status()
        return r.json()

    except requests.HTTPError as e:
        try:
            detail = e.response.json()
        except ValueError:
            detail = e.response.reason
        flash(f"{e.response.status_code} error from {api_name}: {detail}", category='error')

    except requests.RequestException as e:
        flash(f"Error sending request to {api_name}: {e}", category='error')

portal/templates/base.html
<!DOCTYPE html>
<title>{% block title %}{% endblock %} - Metadata Portal</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

<header>
    <nav>
        <h1><a class="nav-button" href="{{ url_for('portal.index') }}">Metadata Portal</a></h1>
        <ul>
            {% if current_user.is_authenticated %}
                <li><span>Hello, {{ current_user.email }}!</span>
                <li><a class="nav-button" href="{{ url_for('hydra.logout') }}">Sign out</a>
            {% else %}
                <li><a class="nav-button" href="{{ url_for('hydra.login') }}">Sign in</a>
            {% endif %}
        </ul>
    </nav>
</header>

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <section class="flash">
            <ul>
                {% for category, message in messages %}
                    <li class="{{ category }}">{{ message }}</li>
                {% endfor %}
            </ul>
        </section>
    {% endif %}
{% endwith %}

<main>
    <header><h1>{% block page_heading %}{% endblock %}</h1></header>
    {% block content %}{% endblock %}
</main>

portal/templates/edit_record.html
{% extends 'base.html' %}
{% from 'macros.html' import field_errors, form_errors %}

{% block page_heading %}
    {% block title %}{{ 'Add' if new else 'Edit' }} Metadata Record - {{ institution_key }}{% endblock %}
{% endblock %}

{% block content %}
    <form method="post">
        {{ form_errors(form) }}
        {{ form.csrf_token }}
        {{ form.collection_key.label }} {{ field_errors(form.collection_key) }}
        {{ form.schema_key.label }} {{ field_errors(form.schema_key) }}
        {{ form.metadata.label }} {{ field_errors(form.metadata) }}
        {{ form.auto_assign_doi.label }} {{ field_errors(form.auto_assign_doi) }}
        {{ form.doi.label }} {{ field_errors(form.doi) }}
        <input type="submit" value="{{ 'Add' if new else 'Update' }} Record">
    </form>
    {% if record %}
        <h2>Result:</h2>
        <textarea style="font-family: monospace; width: 75%; height: 50vh" readonly>
            {{ record }}
        </textarea>
    {% endif %}
{% endblock %}

portal/templates/home.html
{% extends 'base.html' %}

{% block page_heading %}
    {% block title %}Welcome{% endblock %}
{% endblock %}

{% block content %}
    <a href="{{ url_for('portal.list_institutions') }}">Institutions</a>
{% endblock %}

portal/templates/institutions.html
{% extends 'base.html' %}

{% block page_heading %}
    {% block title %}Institutions{% endblock %}
{% endblock %}

{% block content %}
    <ul>
        {% for institution in institutions %}
            <li><h2>{{ institution.name }}</h2>
                <p><a href="{{ url_for('portal.list_records', institution_key=institution.key) }}">List records</a>
                <p><a href="{{ url_for('portal.add_record', institution_key=institution.key) }}">Add record</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

portal/templates/list.html
{% extends 'base.html' %}

{% block page_heading %}
    {% block title %}Metadata Records{% endblock %}
{% endblock %}

{% block content %}
    <form method="post">
        <label>Institution Key:</label><input name="institution_key" type="text">
        <input type="submit" value="Get Records">
    </form>
    {% for record in records %}
        <section class="metadata-record">
            <textarea style="font-family: monospace" readonly>
                {{ record }}
            </textarea>
        </section>
    {% endfor %}
{% endblock %}

portal/templates/list_records.html
{% extends 'base.html' %}

{% block page_heading %}
    {% block title %}Metadata Records - {{ institution_key }}{% endblock %}
{% endblock %}

{% block content %}
    {% for record in records %}
        <section class="metadata-record">
            <textarea style="font-family: monospace" readonly>
                {{ record }}
            </textarea>
            <a href="{{ url_for('portal.view_record', institution_key=institution_key, record_id=record.id) }}">View...</a>
            <a href="{{ url_for('portal.edit_record', institution_key=institution_key, record_id=record.id) }}">Edit...</a>
        </section>
    {% endfor %}
{% endblock %}

portal/templates/macros.html
{% macro field_errors(field) %}
    {% if field.errors %}
        {% set css_class = 'has-error ' + kwargs.pop('class', '') %}
        {{ field(class=css_class, **kwargs) }}
    {% else %}
        {{ field(**kwargs) }}
    {% endif %}
{% endmacro %}

{% macro form_errors(form) %}
    {% if form.errors %}
        <ul class="form-errors">
            {% for field_name, field_errors in form.errors|dictsort if field_errors %}
                {% for error in field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    {% endif %}
{% endmacro %}

portal/templates/view_record.html
{% extends 'base.html' %}

{% block page_heading %}
    {% block title %}View Metadata Record - {{ institution_key }}{% endblock %}
{% endblock %}

{% block content %}
    {% if record %}
        <textarea style="font-family: monospace; width: 75%; height: 75vh" readonly>
            {{ record }}
        </textarea>
    {% endif %}
{% endblock %}